version: '0.1'
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - birthdays_data:/data
    command: python ./app.py
    networks: 
      - my_network
  test:
    build: ./tests
    depends_on:
      - app
    volumes:
      - birthdays_data:/data
      - test-results:/tests/test-results
    command: sh -c "rm -rf /tests/test-results/* && pytest --alluredir=/tests/test-results"
    networks:
      - my_network
  allure_test_report:
    build: ./allure-reporter
    depends_on:
      - test
    volumes:
      - test-results:/app/allure-results
    command: sh -c "allure generate /app/allure-results --clean && allure serve /app/allure-results --port 80 --host 0.0.0.0"
    ports:
      - "8000:80"
    networks:
      - my_network

volumes:
  birthdays_data:
  test-results:

networks:
  my_network:
    driver: bridge
