name: Run tests

on: 
  workflow_dispatch

jobs:

  run-docker-compose:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install docker-compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        
      - name: Set up Docker Compose
        run: |
          docker-compose up --build -d
      
      - name: Print allure files in container
        run: |
          docker-compose exec allure_test_report ls -R

      - name: Copy allure-results from container
        run: |
          docker-compose cp allure_test_report:app/allure-report allure-report
      
      - name: Print allure files
        run: |
          ls -R allure-report
      
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Create Allure report page
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history