name: Run tests

on: 
  workflow_dispatch

jobs:

  run-docker-compose:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          up-flags: |
            --build
            --detach
      
      - name: Copy allure-results from container
        run: |
          docker-compose cp allure_test_report:app/allure-results allure-results
      
      - name: Print allure files
        run: |
          ls allure-results
      
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Create Allure report page
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure/allure-results
          allure_history: allure-history
          keep_reports: 20
      
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history