name: Run tests

on: 
  workflow_dispatch

jobs:

  run-docker-compose:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'
        
      - name: Set up Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose cp allure_test_report:app/allure-results ./allure-results
          docker-compose cp allure_test_report:app/allure-report ./allure-report
          docker-compose down
      
      - name: Create Allure report page
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history