name: Run tests

on: 
  workflow_dispatch

jobs:

  run-docker-compose:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'
        
      - name: Set up Docker Compose
        run: |
          docker-compose up --build -d
          mkdir -p ./allure
          docker-compose cp allure_test_report:app/allure-results ./allure/allure-results
          docker-compose cp allure_test_report:app/allure-report ./allure/allure-report
          ls -R allure
          docker-compose down
      
      - name: Print allure files
        run: |
          ls -R allure
          ls -R allure/allure-results
          ls -R allure/allure-report
      
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Create Allure report page
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure/allure-results
          allure_report: allure/allure-report
          allure_history: allure-history
          keep_reports: 20
      
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history